# Generated by Django 3.0.8 on 2020-07-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
